### ISSUE TITLE
Add UI and server call to change reader for individual manga

### ISSUE THREAD

**Issue by Ligerx** [Ligerx/TachiWeb-React#11]
- You can now get/set a manga's viewer/reader by making a GET/POST request to /api/v2/mangas/[COMMA SEPARATED MANGA IDS]/viewer
    - The possible viewer options are: DEFAULT, LEFT_TO_RIGHT, RIGHT_TO_LEFT, VERTICAL, WEBTOON
    - Default just means whatever viewer the user chooses to use globally. Usually that's stored as a setting but that hasn't been implemented yet so you can just use the LEFT_TO_RIGHT viewer when the viewer for a manga is set to DEFAULT

edit:  related to #36. This is a subset of all the possible settings.

**Comment by Ligerx** [comment]
the server default is already implemented. (I might request that the default be changed to webtoon though)

Include a way to set an individual manga's read preference.

**Comment by Ligerx** [comment]
Asking nulldev if this can just be sent with the library data

**Comment by null-dev** [comment]
@Ligerx Yes it probably could... In fact, it probably should have been but I think I forgot to serialize that particular field. API v1 is such a mess :(
