### ISSUE TITLE
Implement missing library flag features

### ISSUE THREAD

**Issue by Ligerx** [Ligerx/TachiWeb-React#27]
"LAST_READ" and "LAST_UPDATED" sort type.
Library "LIST" view
"show_download_badges"

**Comment by Ligerx** [comment]
I don't believe last read and last updated are implemented.

Also, downloads haven't been implemented yet either.

**Comment by null-dev** [comment]
Last read + last updated are implemented by: https://github.com/Ligerx/TachiWeb-React/pull/39
