### ISSUE TITLE
UI to enable/disable sources

### ISSUE THREAD

**Issue by null-dev** [Ligerx/TachiWeb-React#42]

**Comment by Ligerx** [comment]
Currently extensions are implemented with api v2 and sources with api v1.
I don't see any documentation on api endpoints for how to do this / emulate the existing screen in Tachiyomi.

**Comment by Ligerx** [comment]
@null-dev this is one of the next things I'm considering working on (plus updating catalogue to be more like Tachiyomi). But I don't see any API related to this. Am I missing something?

**Comment by null-dev** [comment]
This should instead be implemented directly in the frontend. Just have a list of the sources that the user has disabled and persist the list under a preference key of your choosing using the `/api/v3/preferences` endpoint.

There actually was an API to do this, but it just did what I described above so I removed it in API v3.

**Comment by Ligerx** [comment]
Is this how it works?

1. Get default language (don't see one in the settings, so I assume just default to english for now)
2. Install a source
2. Disable the source or any sub-source whose language is not english

**Comment by null-dev** [comment]
Actually, I should probably clarify. This is how the original Tachiyomi app does it and it's a little different compared to what you described but I think it's a pretty decent approach:
- Have two lists (persisted in `/api/v3/preferences`) named `enabledLanguages` and `hiddenSources`.
- The only language enabled by default is English
- No sources are hidden by default
- Sources that belong to languages that are not in `enabledLanguages` are hidden from the catalogue
- Sources that exist in `hiddenSources` are also hidden

That way, you don't have to do anything when extensions are installed.

**Comment by Ligerx** [comment]
This is what's currently returned by the api
```
pref_filter_downloaded_key(pin): false
pref_filter_completed_key(pin): false
library_sorting_ascending(pin): true
display_download_badge(pin): false
library_sorting_mode(pin): 0
pref_display_library_as_list(pin): false
pref_default_viewer_key(pin): "left_to_right"
pref_filter_unread_key(pin): false
```

Is the intention that I create my own keys for this? I assumed they would be supplied by default by the api

**Comment by Ligerx** [comment]
Jk, looking at a fresh set of data, it's totally empty.
Does the settings just duplicate other data? Eg. setting library sort/filter options will appear in both library and settings.

**Comment by null-dev** [comment]
Yeah the settings API is just a direct view into Tachiyomi's internal settings where all the stuff like library sort/filter options are stored. You should just create your own preference keys.

As for the enabled languages and sources, just store those in the preferences and default the enabled languages to only English. This should all be handled on the frontend as the enabling/disabling of sources is really only a cosmetic thing and the doesn't affect the backend in any way.

**Comment by null-dev** [comment]
I think the only treatment local manga should get is that the `Open source website` button should be hidden on manga that are from the local source. Obviously you shouldn't use the download API on local manga either but since we are dropping the download functionality altogether, it shouldn't matter.

The source id of local manga will always be: `0`.

**Comment by Ligerx** [comment]
> Obviously you shouldn't use the download API on local manga either but since we are dropping the download functionality altogether, it shouldn't matter.

I'm not familiar at all with the downloading stuff or how local manga work. When you say this do you mean that local manga should be totally ignored, or is it still used?

**Comment by null-dev** [comment]
@Ligerx Oh, no, you should treat local manga as normal, the only special handling you have to do is hide the "Open source website" button.

For the download API, I was talking about this endpoint: `/api/v3/chapters/{chapterId}/download` but you don't have to worry about it as you aren't using that endpoint anyways.
